### ISSUE TITLE
Suggestion: show gradio username+password on last colab cell

### ISSUE THREAD

**Issue by Matsukii** [ddPn08/automatic1111-colab#10]
suggestion: Add Gradio username and password along with URLs on last cell, to make easy to find

It came as surprise when I opened WebUI, I didn't notice that need and can be changed, other people may not find as well...

**Comment by ddPn08** [comment]
sorry for the late reply. This takes into account the gradio URL specification from a while back. I don't really need it now, so I'll fix it to turn it off by default.

**Comment by ddPn08** [comment]
sorry i'm late
fixed here
https://github.com/ddPn08/automatic1111-colab/commit/5102bcb1d175ad385ad86a1e2e971292299fa420
