### ISSUE TITLE
Error on img2img, folder not found

### ISSUE THREAD

**Issue by d0000s00000** [ddPn08/automatic1111-colab#13]
With default configuration, there are errors on txt2img and img2img:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/txt2img-images'
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/img2img-images'
(Creatng of mentioned folders did not help)

**Comment by ddPn08** [comment]
I just fixed it. please make sure.

**Comment by d0000s00000** [comment]
Thank you! You a doing a great job

**Comment by d0000s00000** [comment]
Thank you! You a doing a great job
