### ISSUE TITLE
Extensions can't be installed or run from Google Drive

### ISSUE THREAD

**Issue by xITmasterx** [ddPn08/automatic1111-colab#14]
As the title stated. I wanted to install extensions, specifically DreamArtist to try that one out, but I wasn't able to use it because it released an error that extensions are not allowed because of permissions.

Is there a way for me to use extensions here?

**Comment by ddPn08** [comment]
Can you please post the error log?

**Comment by xITmasterx** [comment]
here's the error log when I tried to install dreamartist extension into the webui:

```
Error completing request
Arguments: ('https://github.com/7eu7d7/DreamArtist-sd-webui-extension.git', ['ads', 'localization', 'installed']) {}
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/stable-diffusion-webui/modules/ui_extensions.py", line 153, in install_extension_from_index
    ext_table, message = install_extension_from_url(None, url)
  File "/content/stable-diffusion-webui/modules/ui_extensions.py", line 117, in install_extension_from_url
    check_access()
  File "/content/stable-diffusion-webui/modules/ui_extensions.py", line 20, in check_access
    assert not shared.cmd_opts.disable_extension_access, "extension access disabled because of command line flags"
AssertionError: extension access disabled because of command line flags
```

**Comment by ddPn08** [comment]
They are problems with AUTOMATIC1111 WebUI and not with this notebook.

You can see that error in this.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Extensions#security

**Comment by xITmasterx** [comment]
Thanks a bunch. Arigato Gozaimasu! (sorry, still learning Japanese and I just started at it.)

**Comment by ddPn08** [comment]
どういたしまして！！
(I got it! I'm learning English at school too...lol)
