### ISSUE TITLE
Error "Can't run without a checkpoint. " on a clean default run.

### ISSUE THREAD

**Issue by d0000s00000** [ddPn08/automatic1111-colab#15]
Thank you for doing a great job, but there is another issue after recent update:

/content/stable-diffusion-webui
Already up to date.
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
Commit hash: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490
Installing requirements for Web UI
Launching Web UI with arguments: --share
No module 'xformers'. Proceeding without it.
No checkpoints found. When searching for checkpoints, looked at:
 - file /content/stable-diffusion-webui/model.ckpt
 - directory /content/stable-diffusion-webui/models/Stable-diffusion
Can't run without a checkpoint. Find and place a .ckpt file into any of those locations. The program will exit.

Clearing folders in Google Drive did not help.
Or maybe i'm doing something wrong.

**Comment by ddPn08** [comment]
Did the setup step create a directory called models/Stable-diffusion in your [DataDirectry](https://github.com/ddPn08/automatic1111-colab/wiki/Data-directory-%7C-EN)?

**Comment by d0000s00000** [comment]
Thank you for the clue, i should have read you description of folders in the link above, where to place .ckpt files.
i've moved my .ckpt file to MyDrive/AI/Automatic1111/models/stable-diffusion/ and it worked!
