### ISSUE TITLE
WD 1.4 Anime not working on Colab free tier due to lack of memory.

### ISSUE THREAD

**Issue by ddPn08** [ddPn08/automatic1111-colab#16]
As the title says. Crash at screenshot position.
![image](https://user-images.githubusercontent.com/71378929/210159780-7112ca06-3a29-4a0e-a287-aa07d5147f55.png)

**Comment by ddPn08** [comment]
unsolvable for now

**Comment by thx-pw** [comment]
解決方法見つけたので共有します。（プルリクがよくわからないので）

Stability-AIのstablediffusionリポジトリをフォークしてURL先のように書き換えると12GBにおさまりました。（2、3GBは余裕がありそう）
https://github.com/thx-pw/stablediffusion/commit/72369d466203f9e4135d53faa085dbc272204607#diff-32753876a979e5de66e59e73a5050e903b45b4fca87f6b1d76d0f6466f5d7c9a

WebUIからこんな感じで呼び出しています。
https://github.com/thx-pw/stable-diffusion-webui-colab/commit/05e9f01634853d2a2bf46dc031228f7a371bfb62#diff-4e26975f9b8609b676775ed846d871493f37b1548aa0234f32fb9dfb2fad38ac

**Comment by ddPn08** [comment]
ありがとうございます！！
無事動作するようになりました！
とても助かりました；；
