### ISSUE TITLE
Systems is generating the images, however, they re not loading into the UI

### ISSUE THREAD

**Issue by ivangarciafilho** [ddPn08/automatic1111-colab#17]
- If i push the params to generate an image greater than 512x768  the image is generated  on the console but not loaded into the UI and the Generate button stop working
- Same thing happens if i try to render 4 images within a single  batch of 384x576 each, or trying to increase the steps from 32 to 64, something is making the images generate correctly (according to the  console output) and not loading them into the UI

**Comment by ddPn08** [comment]
This is a phenomenon that occurs because the gradio share system is unstable. Try using ngrok. It should stabilize a little.
https://github.com/ddPn08/automatic1111-colab/wiki/2.-Launch-preferences-%7C-EN#using-ngrok

**Comment by ivangarciafilho** [comment]
Thanks!  pretty straight forward!  it's working !
