### ISSUE TITLE
The specifications in the latest version of Stable Diffusion have changed.

### ISSUE THREAD

**Issue by tadaimatrpg** [ddPn08/automatic1111-colab#18]
I was able to use Stable Diffusion by 16:00 Japan time (UCT+9), but when I did a RUN according to the wiki, the UI address was not displayed and I could not access the UI although it was running.
I initialized all the contents of my Google Drive, etc., and installed the UI using "Setup environment" in "3 - Launch WebUI". content/stable-diffusion-webui/models/Stable-diffusion", but there was no sd-v1-4.ckpt in the path /content/stable-diffusion-webui/models/Stable-diffusion, and I could not start it.

I downloaded various files with sd-v1-4.ckpt in the path of /content/stable-diffusion-webui/models/Stable-diffusion, but only the UI address was not shown and I could not access it.

What can I do to fix the problem of the UI address not being displayed?
![1](https://user-images.githubusercontent.com/54084706/210219583-46b50642-9bc9-4dec-ab76-d150f249075f.png)

**Comment by ddPn08** [comment]
ngrok is enabled. You can access it using the link ending in `ngrok.io`. Sorry if the screenshot is hard to understand.
![image](https://user-images.githubusercontent.com/71378929/210220736-00db2d33-e148-42e4-b9dc-9466b6035801.png)

**Comment by tadaimatrpg** [comment]
I have successfully accessed the UI!
Thank you very much.
