### ISSUE TITLE
Running on public URL no appears

### ISSUE THREAD

**Issue by Dmalizer** [ddPn08/automatic1111-colab#19]
Greetings, I have this problem when I load the "Running on public URL" no appears, any idea why it happens?

![0001](https://user-images.githubusercontent.com/121835795/210287533-3dfdd38e-6667-4634-ac45-782729858a69.PNG)

**Comment by ddPn08** [comment]
![image](https://user-images.githubusercontent.com/71378929/210304560-55fef4a7-d742-45e9-af03-ba6c0554785f.png)
Please show me all the lines starting with "Launching Web UI with arguments:".

**Comment by catapulta** [comment]
Same problem. Here's the Web UI arguments:
```Launching Web UI with arguments: --xformers --share --gradio-auth user:password```

Thanks for the well maintained colab!

**Comment by ddPn08** [comment]
I see, that behavior is strange.
I think it's probably a bug in [AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui). I will check here as well.

**Comment by ddPn08** [comment]
https://github.com/gradio-app/gradio/issues/2918

**Comment by ddPn08** [comment]
![image](https://user-images.githubusercontent.com/71378929/210367841-2ceced5d-2ddf-4d35-afa7-8c4ac4d28220.png)
As a stopgap measure, it can be fixed by inserting the code below like this:
```
pip uninstall gradio
pip install gradio==3.9
```

**Comment by ddPn08** [comment]
It seems to have been fixed.
https://github.com/gradio-app/gradio/issues/2918#issuecomment-1369850904

**Comment by anabea17** [comment]
![Image](https://github.com/user-attachments/assets/8d4e6883-d222-4d1f-ba52-75651c1fdf58)

**Comment by anabea17** [comment]
Crie um prompt  de 
uma mulher sexy
