### ISSUE TITLE
preparing metadata setup ens in error 

### ISSUE THREAD

**Issue by Japtranslator** [ddPn08/automatic1111-colab#20]
in the final cell i get:

/content/stable-diffusion-webui
Already up to date.
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
Commit hash: a1cf55a9d1c82f8e56c00d549bca5c8fa069f412
Installing xformers
Traceback (most recent call last):
  File "/content/stable-diffusion-webui/launch.py", line 294, in <module>
    prepare_environment()
  File "/content/stable-diffusion-webui/launch.py", line 230, in prepare_environment
    run_pip("install xformers", "xformers")
  File "/content/stable-diffusion-webui/launch.py", line 78, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "/content/stable-diffusion-webui/launch.py", line 49, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install xformers.
Command: "/usr/local/envs/automatic/bin/python" -m pip install xformers --prefer-binary
Error code: 1
stdout: Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting xformers
  Using cached xformers-0.0.13.tar.gz (292 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

stderr:   error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I didn't change any settings,

**Comment by ddPn08** [comment]
![image](https://user-images.githubusercontent.com/71378929/210367310-80f32001-36e3-4daa-a22f-9229960ee3a6.png)
Please enable "force_reinstall_environmemt" and try again.

You can also do a quick fix by disabling xformers. (You cannot use xformers)

**Comment by Japtranslator** [comment]
> ![image](https://user-images.githubusercontent.com/71378929/210367310-80f32001-36e3-4daa-a22f-9229960ee3a6.png) Please enable "force_reinstall_environmemt" and try again.
> 
> You can also do a quick fix by disabling xformers. (You cannot use xformers)

Thank you very much, the reinstall did it. Love your work
