### ISSUE TITLE
styles.csv is no longer keeping data

### ISSUE THREAD

**Issue by samueljacobjackson** [ddPn08/automatic1111-colab#22]
It looks like the styles.csv file is being stored in the stable-diffusion-webui folder and not stored in google drive as it was before.  This makes any changes to the file transient.

**Comment by ddPn08** [comment]
Fixed in this commit.
https://github.com/ddPn08/automatic1111-colab/commit/851d1379239025c9c6c7e033725bdca823196b21

**Comment by ddPn08** [comment]
No, it looks like it hasn't been fixed yet.

**Comment by ddPn08** [comment]
The issue has been fixed.
