### ISSUE TITLE
Deleting my data google drive folder

### ISSUE THREAD

**Issue by JeffreyDSmith001** [ddPn08/automatic1111-colab#24]
I am having a weird bug where the colab deletes my current data folder and replaces it with a new (but mostly empty) folder of the same name. I have my data_dir set as "/content/drive/MyDrive/sd/" which contains a folder by the name of "models" as specified by the colab UI. Then I have the data_dir_gdrive set as "/content/drive/MyDrive/sd/automatic1111". After running step 1.2 - step 3, my original "sd" folder has been moved to the trash, along with everything inside of it, including models, outputs, and settings. I am left with a fresh new "sd" folder that only contains the folders 'Conda-env', 'scripts', 'config', 'outputs', and 'models'.

**Comment by ddPn08** [comment]
sorry. This is my lack of explanation.
`data_dir` must not be a folder in Google Drive. `data_dir` is where it will later be linked to `data_dir_gdrive`. Improve to throw an exception when a folder in Google Drive is specified.

**Comment by JeffreyDSmith001** [comment]
Got it, that fixed the problem. Thank you for your hard work!
