### ISSUE TITLE
Unable to find checkpoint in the AI/models directory

### ISSUE THREAD

**Issue by oliveirabruno01** [ddPn08/automatic1111-colab#26]
Hi

I encountered this issue when running the notebook:

```/content/stable-diffusion-webui
Already up to date.
Python 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
Commit hash: 29fb5327640465fc83111e2170c5d8aa2b15266c
Installing requirements for Web UI
Launching Web UI with arguments: --xformers --share
No checkpoints found. When searching for checkpoints, looked at:
  - file /content/stable-diffusion-webui/model.ckpt
  - directory /content/stable-diffusion-webui/models/Stable-diffusion
Can't run without a checkpoint. Find and place a .ckpt file into any of those locations. The program will exit.
```

I know I could probably fix this just by changing the model directory, but what I don't understand and it frustrates me is that these same directory (AI/models) worked a few months ago. It's the default directory for Deforum Stable Diffusion, for example. Can anyone tell me why the MyDrive/AI/models directory is no longer recognized by default?

**Comment by oliveirabruno01** [comment]
Updating: I tried to put the model in the folders indicated by the error but it didn't work.

**Comment by ddPn08** [comment]
I recently changed my directory structure.
Have a look at this.
https://github.com/ddPn08/automatic1111-colab/wiki/Data-directory-%7C-EN

Stable-diffusion models should be placed in `models/Stable-diffusion`.

**Comment by oliveirabruno01** [comment]
Thank you very much. My mistake, I should have seen the giant breaking change notice lol. Now it's working perfectly again
