### ISSUE TITLE
Possible to map extensions directory for google drive?

### ISSUE THREAD

**Issue by Taubin** [ddPn08/automatic1111-colab#27]
Is it possible to mount the extensions directory in Google Drive? I would like to use the [Dynamic Prompts}(https://github.com/adieyal/sd-dynamic-prompts) extension, however since the extensions directory is not mapped, I'm unable to create the wildcard files. They are normally put in automatic1111\extensions\wildcards however even if I create that directory in google drive it doesn't work. 

Thank you for this colab, it's amazing.

**Comment by ddPn08** [comment]
It used to be impossible, but I think it maybe possible now. So I'll try it.

**Comment by ddPn08** [comment]
This partly worked so I implemented it.
However, this can lead to unexpected errors;
https://github.com/ddPn08/automatic1111-colab/commit/b602670e9f5059153855661441e4ce9cdc66fafa

**Comment by Taubin** [comment]
Thank you so much!
