### ISSUE TITLE
Where is the extensions filepath on gdrive?

### ISSUE THREAD

**Issue by rustyorb** [ddPn08/automatic1111-colab#28]
The option can be toggled and directly beneath that toggle are two github links to extensions, So is it pulling them and storing them on gdrive. What does that toggle do?

Thanks. 

![Screenshot_20230114_083212](https://user-images.githubusercontent.com/111198602/212474670-baa1fb8c-7666-4d33-9ccf-2e9c64e66f0d.png)

**Comment by ddPn08** [comment]
Extensions list files are stored in `{data_dir}/extensions.txt`.
For example, if you set data_dir to `/content/drive/MyDrive/AI/automatic1111`, the file will be stored in `/content/drive/MyDrive/AI/automatic1111/extensions.txt`.

**Comment by rustyorb** [comment]
Ok, That's what I thought, added CivitAI git adress to that file. 

Do I have to add any extensions that I want to persist between uses in this file manually? Or when I install them in Gradio, does it add to the extensions txt file?

Thank you. Good work your doing.

**Comment by ddPn08** [comment]
Currently the only way is to add it manually.
