### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/content/data/models'

### ISSUE THREAD

**Issue by dax-wrld** [ddPn08/automatic1111-colab#29]
Hi!
I'm launching it on a new and clean account. In paragraph 1.2, the same error always occurs.
All parameters are standard.

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-3-bf4aa262dd46>](https://localhost:8080/#) in <module>
     47 extensions_file_path = f"{data_dir}/extensions.txt"
     48 
---> 49 os.makedirs(models_path, exist_ok=True)
     50 os.makedirs(output_path, exist_ok=True)
     51 os.makedirs(config_path, exist_ok=True)

[/usr/lib/python3.8/os.py](https://localhost:8080/#) in makedirs(name, mode, exist_ok)
    221             return
    222     try:
--> 223         mkdir(name, mode)
    224     except OSError:
    225         # Cannot rely on checking for EEXIST, since the operating system

FileNotFoundError: [Errno 2] No such file or directory: '/content/data/models'

**Comment by ddPn08** [comment]
Oh, looks like I was making a big mistake all along...
I fixed it now.
https://github.com/ddPn08/automatic1111-colab/commit/c2251f1f0398ef5091eaaaa547b90bb6ccc32433
