### ISSUE TITLE
Running in iPad safari, nothing popup

### ISSUE THREAD

**Issue by jimys** [ddPn08/automatic1111-colab#3]
Must run in pc?

**Comment by ddPn08** [comment]
sorry. I don't have an IOS machine so I can't try that issue.
However, a similar issue occurred when I ran it in Chrome on Android. At that time, I was able to solve it by enabling the "PC version site" item.

**Comment by ddPn08** [comment]
This issue has been closed because it hasn't any recent activity.

**Comment by Deniz1433** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/4326
This is the solution for this
