### ISSUE TITLE
Save Button does not work

### ISSUE THREAD

**Issue by samueljacobjackson** [ddPn08/automatic1111-colab#31]
The save button no longer saves the file to the outputs/Saved folder in _data_dir_gdrive_/AI/automatic1111/outputs/Saved nor /content/data/outputs/Saved.  No error in the notebook or browser.  I have the new directory structure setup.

**Comment by ddPn08** [comment]
Check the output destination on the Settings tab of the WebUI.

**Comment by samueljacobjackson** [comment]
I see, Thank you.
