### ISSUE TITLE
Do I need VAE?

### ISSUE THREAD

**Issue by ahmedsiha** [ddPn08/automatic1111-colab#35]
Hello, I got this error for the first time. Do I need VAE file now? How do I set it up with custom models? Thank you.

![automatic1111-ipynb-Colaboratory](https://user-images.githubusercontent.com/121781747/214304533-91486a30-5a37-4728-88f3-ad661dfa98b2.png)

**Comment by ddPn08** [comment]
I believe it was fixed in #36
