### ISSUE TITLE
Extracting xformers stuck in latest release

### ISSUE THREAD

**Issue by tommyjohn81** [ddPn08/automatic1111-colab#37]
Getting the following error in Step 3 - Launch WebUI
The extraction of xformers gets stuck and doesn't proceed

==> WARNING: A newer version of conda exists. <==
  current version: 22.11.1
  latest version: 23.1.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.1.0

## Package Plan ##

  environment location: /usr/local/envs/automatic

  added / updated specs:
    - xformers

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    xformers-0.0.16.dev432+git.bc08bbc|py310_cu11.3_pyt1.12.1       292.7 MB  xformers/label/dev
    ------------------------------------------------------------
                                           Total:       292.7 MB

The following NEW packages will be INSTALLED:

  xformers           xformers/label/dev/linux-64::xformers-0.0.16.dev432+git.bc08bbc-py310_cu11.3_pyt1.12.1 

Downloading and Extracting Packages
xformers-0.0.16.dev4 | 292.7 MB  | :   0% 0/1 [00:00<?, ?it/s]

**Comment by tommyjohn81** [comment]
It completed after 25 minutes, maybe it is not an issue after all.

**Comment by ddPn08** [comment]
I changed the python setup script quite a bit earlier.
I think this issue will probably be fixed as well
