### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by SylvianHemus** [ddPn08/automatic1111-colab#38]
I like this repo for automatic1111 ui. I see now dreambooth is added, which is cool. I want to use it. But is there an option to just use the automatic111 ui? I just need to make something very basic and don't need any extra training

**Comment by ddPn08** [comment]
Thank you for using!
Does Dreambooth refer to extensions?
This notebook does not add Dreamboot extensions.

**Comment by SylvianHemus** [comment]
Sorry. I've posted this in the wrong location. I should probably go to bed.
