### ISSUE TITLE
Folder embeddings is not created

### ISSUE THREAD

**Issue by ErnieDiffusion** [ddPn08/automatic1111-colab#40]
Hi, sorry if that is a stupid question, I am a complete beginner.

I used that code with colab an in general it works great - thank you very much!

However, I am not able to train an embedding.

There seems to be an issue with the file directories:
1. I can create an embedding and it says it is stored. I can even start to train it. However, it doesn't seem to be stored. The folder "embeddings" isn't even created and I cannot find a file with the name of the embedding in the Google Drive. Also it completely gone, when I start a new session 
2. Also I noticed that I cannot create (or delete) the textinversion templates. Whatever I do in the folder is not represented in the webui

Can someone please advise?

**Comment by ddPn08** [comment]
Fixed `embeddings` folder to be created by default.
