### ISSUE TITLE
When storing conda on drive: python: bad interpreter: Permission denied 

### ISSUE THREAD

**Issue by Tyde** [ddPn08/automatic1111-colab#44]
Hi, I have set up the notebook to use conda that is stored on Google Drive in the following folder:
`/content/drive/MyDrive/conda/bin/conda`

The first install of the script works fine and it uses conda. But when I restart colab and the script tries to load from conda, it cannot initialize conda and shows this error:

`/bin/bash: /content/drive/MyDrive/conda/bin/conda: /content/drive/MyDrive/conda/bin/python: bad interpreter: Permission denied`

It still goes on to install everything, but it is not doing that in the conda environment and therefore it is only using python version 3.8.10

Somehow this has to do with the permissions in the conda folder. I tried to change the permissions in the conda/bin folder to +x but that isn't enough.

**Comment by ddPn08** [comment]
The feature to save conda environments has been deprecated.
