### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by Rudy34160** [ddPn08/automatic1111-colab#45]
I got the following error when running the script to launch WebUI:

![image](https://user-images.githubusercontent.com/118270456/220212560-8990c769-f9d1-4bd0-a193-c1528155470e.png)

Any idea where the error could come from?

**Comment by Tyde** [comment]
Judging from the error message, could it be that you missed executing step 1.1.?

**Comment by Rudy34160** [comment]
> Judging from the error message, could it be that you missed executing step 1.1.?

That's right...
