### ISSUE TITLE
Additional Networks cannot read Lora data

### ISSUE THREAD

**Issue by syou97** [ddPn08/automatic1111-colab#46]
<img width="665" alt="スクリーンショット 2023-02-26 16 58 20" src="https://user-images.githubusercontent.com/91255337/221399018-595e8d44-de18-411f-bdcb-0391b41d9507.png">
Model cannot be selected except None. Please help.

**Comment by ddPn08** [comment]
![image](https://user-images.githubusercontent.com/71378929/221411650-846c08ab-25b3-4661-beae-a1535e6f93de.png)
The folder containing LoRA for Additional Networks can be set from the Settings tab.

**Comment by syou97** [comment]
Thnak you!!!!
I am ready.
I want to thank you. Thank you for making a nice notebook.
