### ISSUE TITLE
Checkpoint not downloaded from Google Drive

### ISSUE THREAD

**Issue by deeplearn-art** [ddPn08/automatic1111-colab#7]
In the Load model cell, I have specified path to my gdrive, where the checkpoint resides. 
After cell execution, it outputs the paths correctly:
```
models_path: /content/drive/MyDrive/AI/models
output_path: /content/drive/MyDrive/AI/automatic1111/outputs
config_path: /content/drive/MyDrive/AI/automatic1111/config
```
However, when running the "Run script" cells, it complains that it could not find the checkpoint 
/content/stable-diffusion-webui/model.ckpt
I can get around this by copying the checkpoint there, but is this expected behavior?

**Comment by ddPn08** [comment]
I haven't been able to reproduce the problem.
Are model files saved in GoogleDrive?
If possible, please send me the log of the "Run script" cell.

**Comment by Matsukii** [comment]
Had same problem here
Just need to copy model (.ckpt file) into AI/models/ folder on your drive

![image](https://user-images.githubusercontent.com/28326534/202296550-d8413a0f-71eb-4dab-81d7-751c68848450.png)

**Comment by ykurilov** [comment]
Same today: 

No checkpoints found. When searching for checkpoints, looked at:
 - file /content/stable-diffusion-webui/model.ckpt
 - directory /content/stable-diffusion-webui/models/Stable-diffusion
Can't run without a checkpoint. Find and place a .ckpt file into any of those locations. The program will exit.

**Comment by ykurilov** [comment]
On Setup Models step:

/content
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1125  100  1125    0     0   2884      0 --:--:-- --:--:-- --:--:--  2877
Warning: Failed to create the file 
Warning: /content/drive/MyDrive/AI/automatic1111/models/Stable-diffusion/sd-v1-
Warning: 4.ckpt: No such file or directory
  0 4067M    0 10136    0     0  22228      0 53:18:12 --:--:-- 53:18:12 22228
curl: (23) Failed writing body (0 != 10136)

**Comment by EelUnamsked** [comment]
**Do this:**

1.2 Setup models
Set up the StableDiffusion model.
Model Path Variables
data_dir: /content/drive/MyDrive/AI/automatic1111/models/Stable-diffusion/


**Or read this for more info:**

https://github.com/ddPn08/automatic1111-colab/wiki/Data-directory-%7C-EN

**Comment by ddPn08** [comment]
Close the issue, considering it's probably resolved. Please reopen if you still need help.
