### ISSUE TITLE
Generated images are not saved in the google drive /outputs folder but in the google colab /outputs folder

### ISSUE THREAD

**Issue by andresj-sanchez** [ddPn08/automatic1111-colab#8]
Greetings!
# What happened?
After running the Google Colab notebook mounting my Google Drive, I generate an image but the image is saved on the outputs folder of the automatic1111 folder on Google Colab.
```
/content
Local Path Variables:

Mounted at /content/drive
Model already downloaded, moving to next step
/content/stable-diffusion-webui
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  332M  100  332M    0     0   224M      0  0:00:01  0:00:01 --:--:--  359M
curl: Saved to filename 'GFPGANv1.3.pth'
models_path: /content/drive/MyDrive/AI/models
output_path: /content/drive/MyDrive/AI/automatic1111/outputs
config_path: /content/drive/MyDrive/AI/automatic1111/config
```
This is the output of the "1.2 setup models" cell, it seems that the Google Drive output folder path is correct, and the model and configuration files seem to be saved correctly in Google Drive. so I don't know what could be causing the error or if this is the expected behavior and I have to manually save the images to the /outputs folder in Google Drive
# Steps to replicate the error
Check "mount_google_drive" checkbox on "1.2 setup models" cell, Run Google Colab notebook, generate an image
# Expected behavior
The images should be saved on the /content/drive/MyDrive/AI/automatic1111/outputs folder inside Google Drive if "mount_google_drive" checkbox is checked
# Possible solution
I managed to get the images saved in Google Drive by editing the AI/automatic1111/config/config.json file in Google Drive as follows
```
...
"outdir_txt2img_samples": "../drive/MyDrive/AI/automatic1111/outputs/txt2img-images",
"outdir_img2img_samples": "../drive/MyDrive/AI/automatic1111/outputs/img2img-images",
"outdir_extras_samples": "../drive/MyDrive/AI/automatic1111/outputs/extras-images",
"outdir_grids": "",
"outdir_txt2img_grids": "../drive/MyDrive/AI/automatic1111/outputs/txt2img-grids",
"outdir_img2img_grids": "../drive/MyDrive/AI/automatic1111/outputs/img2img-grids",
...
```
It seems that just editing the file once is enough to make the configuration last every time you run Google Colab, but it is a manual process, I don't know if there is a solution that could be added to the Google Colab notebook to do this automatically when it is used for the first time.

**Comment by ddPn08** [comment]
Currently, there is no way to change the output destination with command line arguments, so config.json with the output destination is generated only if there is no that.
If it seems that the json editing process can be written simply, I will add it as an option.

**Comment by ddPn08** [comment]
This has been improved with the DataDirectory implementation.
